version: "3.9"
services: 
  php:
    image: php:8.2.1-fpm
    build:
      context: .
      dockerfile: mysql.Dockerfile
    volumes: 
      - './dev:/var/www/html'
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './dev:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
      - './docker/nginx/ssl:/etc/nginx/ssl'
      - './docker/nginx/snippets:/etc/nginx/snippets'
    depends_on:
      - php

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
    - './docker/volume/mysql:/var/lib/mysql'
    ports:
    - "3306:3306"
